### PR TITLE
Testing testing

### PR DESCRIPTION
**Pull request by MonsterIestyn**
Don't approve this, I just wanted to see whether appveyor succeeds or not, since it spouted errors unrelated to the changes in my other pull request (md2-interpolation-fix).

### CODE REVIEW

**Comment by MonsterIestyn** [comment]
Yep, appveyor fails, doesn't like fallthroughs for whatever reason.

**Comment by alama** [comment]
There because it is now using GCC 7.2

**Comment by MonsterIestyn** [comment]
What's strange though is this is even with the `/* FALLTHRU */` comments you added recently, as far as I can tell. And yet it errors for every single one of them, seemingly.

**Comment by alama** [comment]
try changing appveyor config from GCC63=1to GCC72=1

**Comment by MonsterIestyn** [comment]
Trying to figure out how to mirror GitLab repo to GitHub repo rn, bear with me

**Comment by MonsterIestyn** [comment]
Nope nevermind I don't know what I'm doing here, update the GitHub repo for me please Alam?

**Comment by MonsterIestyn** [comment]
https://ci.appveyor.com/project/STJr/srb2/build/2.1.19.master-1395/job/xqeknu8kf1cu3fnj

appeveyor still failed...

disable the error maybe? unless there's some way to figure out what's wrong with it

**Comment by MonsterIestyn** [comment]
All checks work, so no need for this now

**Pull request closed without merging**
