### PR TITLE
Unify implementations of SetPalette

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by alama** [comment]
Just to note, you may have better luck if you make a merge request on our GitLab, https://git.magicalgirl.moe/STJr/SRB2/merge_requests

**Comment by ccawley2011** [comment]
> Just to note, you may have better luck if you make a merge request on our GitLab, https://git.magicalgirl.moe/STJr/SRB2/merge_requests

Unfortunately, I'm not able to sign in. I tried using "Sign in with GitHub", but it just reports "Your account has been blocked. Please contact your GitLab administrator if you think this is an error.". [It does seem to have created the account though](https://git.magicalgirl.moe/ccawley2011), so I'm not sure what went wrong.

**Comment by jameds** [comment]
Last I heard, the sign in with github feature was broken. It may work if you register an account directly.

**Comment by alama** [comment]
This git repository is just a mirror of https://git.do.srb2.org/STJr/SRB2/

You may have better luck merging code there.

**Pull request closed without merging**
