### PR TITLE
readme.txt duplicated, also incorrect

### PR DESCRIPTION
**Pull request by mdeguzis**
readme.txt should be README.md. The debian build will fail without this change

### CODE REVIEW

**Comment by mdeguzis** [comment]
Actually the entire debian/ folder seems to need an overhaul to make use of the cmake build system.

**Comment by alama** [comment]
If you wish to do so, you may...

**Comment by mdeguzis** [comment]
I don't mind at all. I'll submit a new PR. Really, it will just follow a similar process the Travis build does.

**Comment by mdeguzis** [comment]
In the interest of keeping things simple, can you just fix the readme file noted?

**Comment by alama** [comment]
well, now, I could wait for the 2 MacOS builds for "verify" to commit

**Pull request merged**
