### PR TITLE
More extra emblems

### PR DESCRIPTION
**Pull request by TehRealSalt**
toaster told me to make this a pull request instead of making it my own private exe

### CODE REVIEW

**Comment by MonsterIestyn** [comment]
Rob requests the max extra emblems limit be even higher, to prevent similar problems in the near future. 512 should do it, you okay to do that for us?

**Comment by TehRealSalt** [comment]
Sure, I don't mind; personally 512 sounds like overkill, but I doubt anyone would complain about that so c:

**Comment by alama** [comment]
Then why not add a commit to the exexemblems to up the number to 512?

**Comment by STJrInuyasha** [comment]
[15:13:40] <@Inuyasha> SRB2 does not provide the mechanic you want
[15:13:57] <@Inuyasha> And hacking up a mechanic that vaguely works is not something I will tolerate
[15:14:32] <@Inuyasha> "for the sake of this one mod, let's make it worse for everybody else"

**Pull request closed without merging**
