### PR TITLE
Fix remote viewpoint cameras for real this time

### PR DESCRIPTION
**Pull request by monster-psychic-cat**
I'm so sorry

### CODE REVIEW

**Comment by SteelTitanium** [comment]
:+1:

**Comment by mazmazz** [comment]
👍  confirmed working on a [test WAD](https://git.magicalgirl.moe/STJr/SRB2/uploads/e050ff3e3252dcff1180e72ccdb56e76/isometric.wad)

**Comment by MonsterIestyn** [comment]
wait a minute, shouldn't this be merged to next rather than master?

**Comment by monster-psychic-cat** [comment]
yeah

**Pull request merged**
