### PR TITLE
Separate dust devil audio/visual and physics

### PR DESCRIPTION
**Pull request by DabirSA**
Allows the dust devil's thinker to be used as an action without audio/visual, without physics, or, for whatever reason, without either.

### CODE REVIEW

**Comment by MonsterIestyn** [comment]
This won't work, we don't code actions in C this way.

If you see how the other actions are coded, `var1` and `var2` are not part of the function signature at all but are global variables that can be set anywhere used by any action in `p_enemy.c`. Two INT32 variables `localvar1` and `localvar2` are usually made to save the current `var1`/`var2` values in case they were changed mid-execution for some action that may be called in-between, though in theory you could give them names like the ones you were directly putting in the function signature.

```C
void A_ExampleAction(mobj_t *actor)
{
	INT32 localvar1 = var1;
	INT32 localvar2 = var2;
	// declare other variables here

	if (LUA_CallAction("A_ExampleAction", actor))
		return;
	// rest of code for action
}```

Something tells me also you haven't been coding in C very long, since you've put `	if visual != 0` and `if physics != 0` with no ( or ) around the expressions (as in `if (visual != 0)`). This at least is very easy to fix.

**Comment by DabirSA** [comment]
> This won't work, we don't code actions in C this way.
> 
> If you see how the other actions are coded, `var1` and `var2` are not part of the function signature at all but are global variables that can be set anywhere used by any action in `p_enemy.c`. Two INT32 variables `localvar1` and `localvar2` are usually made to save the current `var1`/`var2` values in case they were changed mid-execution for some other action that may be called by the action itself (directly or directly), though in theory you could give them names like the ones you were directly putting in the function signature.
> 
> ```c
> void A_ExampleAction(mobj_t *actor)
> {
> 	INT32 localvar1 = var1;
> 	INT32 localvar2 = var2;
> 	// declare other variables here
> 
> 	if (LUA_CallAction("A_ExampleAction", actor))
> 		return;
> 	// rest of code for action
> }
> ```

Understood.

> Something tells me also you haven't been coding in C very long, since you've put ` if visual != 0` and `if physics != 0` with no ( or ) around the expressions (as in `if (visual != 0)`). This at least is very easy to fix.

I've known C most of my life, but working with LUA more recently had me confused.

**Comment by MonsterIestyn** [comment]
Fair enough then, I guess one can get the two languages mixed up sometimes. :laughing:

**Comment by SteelTitanium** [comment]
The target branch should be set to next. 

`master` should only be used if you are fixing an issue with compiling, such as addressing warnings introduced by a new version of GCC or updating a build bot's config.

**Comment by DabirSA** [comment]
> 
> 
> The target branch should be set to next.
> 
> `master` should only be used if you are fixing an issue with compiling, such as addressing warnings introduced by a new version of GCC or updating a build bot's config.

Sorted.

**Pull request closed without merging**
