### PR TITLE
Hotfix: Lua thinkers.iterate

### PR DESCRIPTION
**Pull request by Yukitty**
Rewrote Lua function `thinkers.iterate` to avoid crashing (and continue iterating correctly) if thinkers are removed while iterating. It accomplishes this by prematurely pushing the next thinker to its internal state and using that to continue if the provided thinker is an invalid userdata.

Test script:
```
COM_AddCommand("test_remove", function()
	for mo in thinkers.iterate("mobj") do
		assert(mo.valid)
		if not mo.player then
			P_RemoveMobj(mo)
		end
	end
end)

COM_AddCommand("average_srb2_user", function()
	for mo in thinkers.iterate("mobj") do
		assert(mo.valid)
		if not mo.snext.player then
			P_RemoveMobj(mo.snext)
			for mo2 in thinkers.iterate("mobj") do
				assert(mo2.valid)
				if not mo2.player then
					P_RemoveMobj(mo2)
				end
			end
		end
	end
end)
```

Caveats:
* If the current thinker is a full userdata which became invalidated and next thinker was _also_ a full userdata which became invalidated (eg. the next mobj in a mobjs loop was removed immediately before we got there), the script is halted with a Lua error.
* Thinkers besides mobjs are still pushed as light userdata and therefore have no means of being validated, as Lua does not interact with them.

### CODE REVIEW

**Comment by alama** [comment]
Can you add CircleCI buildbot to your fork?

**Comment by Yukitty** [comment]
Still considering alternatives.

**Comment by Yukitty** [comment]
It may be complete now.
I only had to rewrite this entire file three times...

**Comment by toasterone** [comment]
...why was this merged? MI and I wanted to take a look at it when we got a moment.

**Pull request merged**
