### PR TITLE
Added transmaps to non modifying lump list.

### PR DESCRIPTION
**Pull request by frozenLake**
After going back over my PMs from the Message Board, I found myself wondering "Why _do_ transmaps cause a game modification, and is there anything I can do to prevent this?"

This was my solution.

Unfortunately its also untested, as I don't have a build environment set up, but judging from the surrounding code, such a fix should work.

I have no idea if this affects netgames in a manner that would cause desyncing.

Note that I /suppose/ that if another lump started with TRANS, say, a texture named TRANSEGG, or TRANS2S8, those might be able to be modified by this, but such a thing would require changes to the other listed names to make this impossible with any of them that its just not feasible.

### CODE REVIEW

**Comment by toasterone** [comment]
:+1: Very reasonable. I'll note that although you WOULD be able to make random lumps that start with the letters "TRANS" (#relatable), you wouldn't be able to make them do anything (#doublerelatable) because you'd need *_START/*_END (for both Sprites and TeXtures). So the downsides which you're suggesting? Wouldn't be a problem in practice!

**Comment by SteelTitanium** [comment]
👍

**Comment by MonsterIestyn** [comment]
Hm, no objections to this here, though does it matter much that this is being merged to master rather than next?

**Comment by toasterone** [comment]
Oh, good point. This should be for Next only.

**Comment by toasterone** [comment]
Why'd you close it? :?

**Comment by SteelTitanium** [comment]
It's already set to be merged into next, so no problems here.

**Comment by MonsterIestyn** [comment]
hm, next probably needs to be uptodate with master here on GitHub (I've already done so on GitLab)

**Comment by frozenLake** [comment]
Ah sorry: I closed it because I thought I screwed up the branch merge with next, so I was about to remake it with next as the original base.

I guess its fine now though? Thanks, Alam.

**Pull request merged**
