### PR TITLE
Allowteamchange fix

### PR DESCRIPTION
**Pull request by alama**
Fixes "allowteamchange no" to actually work properly and NOT desync you from the game in most cases. You can now switch TO spectator freely (as intended it turns out), and switching FROM spectator is prohibited. The "Enter Game" menu option in Match/Tag now displays one of those blue window notices just like with "Change Teams" in CTF/Team Match if you cannot change teams right now. Everything else works as you'd expect.

The de-sync issue was originally reported here https://mb.srb2.org/showthread.php?p=789965#85

### CODE REVIEW

**Comment by MonsterIestyn** [comment]
Is appveyor not working? I just noticed this and chi's custom wipes thing are stuck on "waiting for status to be reported".

**Comment by alama** [comment]
maybe due that I had to revoke and renew my GitHub tokens due to CloudFlare's "issue"

**Comment by MonsterIestyn** [comment]
Came across these messages reading the SDL console log (even though SDL did compile fine):
`C:\msys64\mingw32\bin\objdump.exe: Dwarf Error: Could not find abbrev number 106.`

There are a TON of them, and seemingly they cycle through the same 5 numbers at a glance: 106, 88, 23, 1295, 4549

Wasn't sure where else to put this since I'm on my laptop right now, thought it may be worth mentioning.

**Comment by alama** [comment]
the binutils tool objdump can not read some the Dwarf (Debugging info) when we are dumping the EIP file:number

**Pull request merged**
