### PR TITLE
Fix Master Server requests and player joins stopping file downloading

### PR DESCRIPTION
**Pull request by LJSonik**
This fixes the bug that caused in-game file downloading to stop after some time for no apparent reason.
To be a bit more specific, it would happen whenever a packet from a non-connected node, such as a join request from a player or a Master Server request (I think?) was received.
The fix is only effective if used on server side and is irrevelant on client side, though it is entirely netgame-compatible with official builds

### CODE REVIEW

**Comment by SteelTitanium** [comment]
Everything looks good :+1:

**Comment by toasterone** [comment]
The code is fine, and it works. But I'm not willing to give you a plusone for reasons I described on the Discord, at least until you investigate alternatives.

For those who don't feel like reading backscroll: This merge request would effectively formalise the mixup between node IDs and player IDs. Whilst it's possible we're *way* too steeped in this mistake to ever get out, I'd like to believe there's still a chance our code could become less fucked some day. Therefore, I can't condone it for now, especially since you're actively willing to look at all the MAXPLAYERS/MAXNETNODES situations and determine which should be which at each point in the code.

If you do eventually give up, I'll relent and go for this (something _is_ better than nothing, after all), adding a bunch of comments to explain why I wasn't happy with the concept when it was first proposed and provide a signpost for future travelers. But you're the one that fixed the netcode. What's a few confused constants to you? ^\_~

**Comment by MonsterIestyn** [comment]
If we could clarify what in particular the game doesn't like when this fix is in without the d_clisrv.c hack, maybe we would be able to do away with it in theory...

Other than that, I have no objections to this going in if the node/player problem isn't already sorted by things such as the Resynch fixes PR. (basically I'm just in the same position as toaster was above, sort of)

**Comment by toasterone** [comment]
I'm thawing on this, but *please* add a line explaining what's going on with this hack, rather than just "**_// OMFG SAY WELCOME TO TEH NEW HACK FOR FIX FIL DOWNLOAD!!1!_** "

Once you've done that, I'll plusone.

**Comment by toasterone** [comment]
👍

**Pull request merged**
