### PR TITLE
Use keysyms for text input

### LINKED ISSUE #444: Use keysyms for text input
I'm using colemak as keyboard layout, which works fine for movement and other controls, wasd is automatically mapped to wars since (I presume) keycodes are used for the keyboard input.

However, when using text input, keysyms should be used instead so that the correct keys are input.

I found the problem in several places, amongs which: editing a server name, typing in the console and chatting in a multiplayer game.

### PR DESCRIPTION
**Pull request by JJK96**
This uses the keycode for chat, console and menu input.
Fix #444

### CODE REVIEW

**Comment by alama** [comment]
So, did you test if this even can compiled?

**Comment by JJK96** [comment]
Yes, I played this version this afternoon.

**Comment by alama** [comment]
Did you compile with `ERRORMODE=1` ?
or even with `clang` as the compiler?

**Comment by alama** [comment]
Look at https://travis-ci.org/STJr/SRB2/jobs/637899901#L1127

**Comment by JJK96** [comment]
> Did you compile with `ERRORMODE=1` ?
> or even with `clang` as the compiler?

I wasn't aware that I should. I just followed [this guide](https://wiki.srb2.org/wiki/Source_code_compiling) which does not state that clang should be used.

I tried the two changes to my make build, but no change in the output compared to my original build.

I compiled again using cmake and clang and I could reproduce the issues.
But I also get some opengl errors (which also happen on the master build):
```
error: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Werror,-Wnull-pointer-arithmetic]
                                pglVertexPointer(3, GL_SHORT, sizeof(vbotiny_t), BUFFER_OFFSET(0));
```

Anyway, I pushed some fixes, but the CI build still fails.

**Comment by JJK96** [comment]
I fixed an issue with mouse input triggering the console window.

**Comment by alama** [comment]
Oh, do not worry about that, SOMEONE merged some changes to networking code without checking if a `NONET=1` build would compile. Do not worry about that, will fixed in [MR!669](https://git.magicalgirl.moe/STJr/SRB2/merge_requests/699), I will ignore that build fail

**Comment by alama** [comment]
This git repository is just a mirror of https://git.do.srb2.org/STJr/SRB2/

You may have better luck merging code there.

**Pull request closed without merging**
